
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { NextUIProvider } from "@nextui-org/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className + " m-h-[100vh]"}>
        <SessionProvider>
          <NextUIProvider>
            {children}
          </NextUIProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
